### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by aliciapaz**
New repository for New York Times article, following the GitFlow.
We copied the code from a previous repository that didn't follow this requirement and hence was invalid.

Main features of the project: 
- Navigation bar fixed at the top
- Use of semantic tags for nav, footer, figure, video, etc.
- Figure with text on top positioned with position relative and absolute
- Embedded video code
- Bottom panel with cards and articles links, positioned with Flexbox
- Use of transition and hover effects

### CODE REVIEW

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Requested :recycle: 
Hello @aliciapaz  and @jaimdedan :wave: 
You guys have done an amazing job in making this clone on your first try :clap: The clone looks nice.
There are some changes that you still need to make 
- [x] Github action is not working on this project and that is because misnamed the folder. It should be .github/workflows. Please update the folder name and make sure that the Github action is being run on your project when you push.
- [x] The screenshot in your readme is not loading up and the live link of the project you added to the readme does not load up the project on the browser. Please update your readme accordingly.
- [x] The margin to the left and right of your nav is too much. Check the screenshot below and update the nav to look like the webpage you cloned.
- your clone 
Screenshot from 2020-11-26 18-57-25
- original
Screenshot from 2020-11-26 19-01-44
- [x] Your clone is missing an aside editor's pick section. Please add that section and remember to use an aside tag for it and float to position to the right.
- original
Screenshot from 2020-11-26 19-04-11
- [x] The most popular section and the footer of your clone is too jampacked. You need to space them just as it is spaced in the original webpage.
- your clone
Screenshot from 2020-11-26 19-06-46
Screenshot from 2020-11-26 19-07-19
- original
Screenshot from 2020-11-26 19-08-24
Screenshot from 2020-11-26 19-08-45
- [x] A requirement for this project is that you use the combination of float, flex, and grid in positioning elements. I suggest you use float for the aside editor's pick section and grid for the theory of inflation section.
- [x] You are expected to build the theory of inflation section from scratch, which means not using the full image the way you are using it currently. You could take screenshots of the individual images that make up that section and use grid to position them to look like it is in the original.  

When you are done making these changes, please request another review.
slack(@ebeagusamuel)

**Comment by aliciapaz** [comment]
- Update .github/workflow folder
- Add screenshot.png and update Github page link. The link will not work until we merge the feature branch with the main.
- Fix margin of the navbar
- Create Editor's Pick aside and position it with float
- Fix width of Most Popular and Footer sections
- Re-do of Theory of Inflation image with a grid

Thank you.

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Requested :recycle: 
Hello :wave: , it is me again.
I must commend you for making changes as requested in the previous review.
Your project looks better now but still has some fixes that you need to make.
- [x] The link to your project that you specified in the read me is still not loading up your project.
- [x] You have some linters errors in your CSS, please fix them.
- [x] The nav is missing some part, i.e the login link. This is how it appears 
Screenshot from 2020-11-26 23-37-57
but it should look like this
Screenshot from 2020-11-26 23-39-16
- [x] The images in the theory of inflation section are not loading. This must be because of how you are specifying the path to the images. It should be specified like this './inflation-img/....' If you don't provide the absolute path, it might work well in development but will have issues when you deploy to a production environment.
Screenshot from 2020-11-26 23-44-56

Request another review once you make these changes
slack(@ebeagusamuel )

**Comment by aliciapaz** [comment]
- Update README.md with raw.githack link to demo page
- Fix linters errors in css
- Fix max width of top menu for more responsiveness
- Update path to theory of inflation images

Thank you

**Review by ebeagusamuel — APPROVED** [review]
# Project Approved :100: 
Congratulations team :clap: :clap: 
This project looks beautiful and your persistence in making the required changes is commendable.
You can now go ahead and merge this branch and good luck with the next project. :+1: 
slack(@ebeagusamuel)

**Pull request merged**
